version: '3'

services:
    mongo:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - 27017:27017
      
    webnode:
      container_name: joournal_back
      restart: always
      build: .
      ports: 
          - "3000:3000"
      # links:
      #   - mongo
      volumes:
        - .:/usr/src/app
        
    # mongo:
    #   container_name: mongo
    #   image: mongo
    #   restart: always
    #   ports:
    #     - 27017:27017
    # db:
    #   constainer_name: mongodb
    #   image: mongo
    #   restart: always
    #   ports:
    #     - 27020:27017
    #   environment:
    #     MONGO_DATABASE: diary_app
    #   volumes:
    #   - ./mongo:/data/db